#!/bin/bash
args=()
for arg in "$@"; do
  if [[ "$arg" == "--remote-tab" ]]; then
    args+=("--remote")
  else
    args+=("$arg")
  fi
done
# Not super necessary
export PATH="${PATH#*lazygit-helpers/:}"
$_NVIM_REAL_PATH "${args[@]}"
