#!/bin/bash
tty="$1"
if [[ $(uname) == "Darwin" ]]; then
  pgrep 'nvim' | xargs ps -o tty= -o state= -o args= -p | rg "^$tty +[^TXZ ]+(.*)" -m1 -o -r '${1}'
else
  ps -o state= -o args= -t "$tty" | rg '^[^TXZ ]+ +(\\S+\\/)?(n?vim .*)' -m1 -o -r '${2}'
fi

