#!/bin/bash

read -r is_nvim nvim_server <<EOF
  $(tmux display -p '#{@is_nvim} #{@nvim_server}')
EOF
read -ra prog <<< "${@:-lazygit}"
lg_helper_dir="$TMUX_SCRIPTS_PATH/lazygit-helpers/"
nvim_args=()
if [ "$is_nvim" = 1 ]; then
  # lazygit doesn't use EDITOR/VISUAL but maybe can hack NVIM
  NVIM="$nvim_server"
  hack_path="$lg_helper_dir:$PATH"
  nvim_args=(-e NVIM="$NVIM" -e PATH="$hack_path")
fi
"$TMUX_SCRIPTS_PATH/popup"  \
  -e DELTA_FEATURES="$DELTA_FEATURES" \
  -e LG_CONFIG_FILE="$LG_CONFIG_FILE,$lg_helper_dir/config.yml" \
  "${nvim_args[@]}" \
  -- "${prog[@]}"

res=$?
# Hack to allow us to silently kill ourselves
if [ $res -eq 129 ]; then
  exit 0
fi
exit $res
