#!/bin/zsh

function __do_make_tmux_wrappers() {
  local script_dir
  if (( ${#BASH_SOURCE[@]} > 1 )); then
    # If the script is sourced (Bash): BASH_SOURCE will have more than 1 element
    script_dir=$(dirname "${BASH_SOURCE[0]}")
  elif [[ -n "$ZSH_VERSION" ]]; then
    # If it's Zsh, no idea how this works but chatgpt said so
    script_dir=$(dirname "${(%):-%x}")
  else
    return 1
  fi
  local src_dir="${SRC_DIR:-$script_dir/../escape-nav/}"
  local out_dir="${OUT_DIR:-"$src_dir/bin"}"
  mkdir -p "$out_dir"
  local compilers=(g++ clang++)
  if [[ -z $CXX ]]; then
    for c in "${compilers[@]}"; do
      if command -v "$c" >/dev/null 2>&1; then
        CXX="$c"
        break
      fi
    done
  fi
  if [[ -z $CXX ]]; then
    echo "Error: No C++ compiler found (searched ${compilers[@]})"
    exit 1
  fi

  function __do_make_tmux_wrapper() {
    local program=$1
    local program_uppercase=$(echo "$program" | tr '[:lower:]' '[:upper:]')

    function c_quoted_args() {
      local result=""
      for arg in "$@"; do
        # Escape any quotes and add double quotes around each argument
        result+='"'"${arg//\"/\\\"}"'"',
      done

      result=${result%,}

      echo "$result"
    }

    function increment_tmux_counter_cmd() {
      local op=$1
      c_quoted_args '$_TMUX_REAL_PATH' set -pFt '$TMUX_PANE' @escape_nav_keys "#{e|${op}:#{@escape_nav_keys},1}"
    }

    $CXX -O2 "$src_dir"/wrap.cpp -o "$out_dir/$program" \
      -DPROGRAM="\$_${program_uppercase}_REAL_PATH" \
      -DBEFORE_CMD="$(increment_tmux_counter_cmd +)" \
      -DAFTER_CMD="$(increment_tmux_counter_cmd -)" \
      -DBALANCED \
      # -DDEBUG
  }

  for prog in "$@"; do __do_make_tmux_wrapper "$prog"; done
}

__do_make_tmux_wrappers "$@"
