#!/bin/bash

DIR=$("$TMUX_SCRIPTS_PATH/get-cwd") &&
  exec tmux popup -E -w 95% -h 95% -T "${@: -1}" \
  -S "fg=$(tmux display -p '#{@thm_lavender}')" \
  -s "bg=$(tmux display -p '#{@thm_mantle}')" \
  -e COLORTERM=truecolor \
  -e TMUX_POPUP=1 \
  -d "$DIR" \
  "$@"

